language: python
python:
  - 3.6.3

services:
  - postgresql

install:
  - pip install -r requirements.txt
env:
  - ENV_VAR=testing

before_script:
  - psql -c 'CREATE DATABASE testing_db;' -U postgres

script:
  - nose2 --with-coverage --cover-package=tests
  
after_success:
  - coveralls
  - codeclimate