language: python
python:
  - 3.6.3
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
before_script:
  - psql -c 'CREATE DATABASE yummy_db2;' -U postgres
  - psql -c 'CREATE DATABASE testing_db;' -U postgres

env:
  DATABASE_URL = 'postgresql:///testing_db'

script:
  - nosetests --with-coverage --cover-package=app
  
after_success:
  - coveralls
  - codeclimate