"""empty message

Revision ID: 9623c6f7eda7
Revises: 6eb8ea75a80c
Create Date: 2018-01-09 12:08:21.278931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9623c6f7eda7'
down_revision = '6eb8ea75a80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('categories',
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category_description', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='categories_created_by_fkey'),
    sa.PrimaryKeyConstraint('category_id', name='categories_pkey'),
    sa.UniqueConstraint('category_name', name='categories_category_name_key')
    )
    # ### end Alembic commands ###
