'''empty message

Revision ID: 9fa42627ae15
Revises: 3ec9494b889c
Create Date: 2018-01-18 04:07:11.477176

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa42627ae15'
down_revision = '3ec9494b889c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipies', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recipies', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipies', type_='foreignkey')
    op.drop_column('recipies', 'created_by')
    # ### end Alembic commands ###
