"""empty message

Revision ID: c85ccb9bb68e
Revises: 1621506b8bca
Create Date: 2018-01-12 07:58:45.701280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85ccb9bb68e'
down_revision = '1621506b8bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipies',
    sa.Column('recipie_id', sa.Integer(), nullable=False),
    sa.Column('recipie_name', sa.String(length=100), nullable=False),
    sa.Column('ingredients', sa.String(length=256), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('recipie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipies')
    # ### end Alembic commands ###
